/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package confluence

import (
	"encoding/json"
)

// checks if the CreateInlineCommentModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateInlineCommentModel{}

// CreateInlineCommentModel struct for CreateInlineCommentModel
type CreateInlineCommentModel struct {
	// ID of the containing blog post, if intending to create a top level footer comment. Do not provide if creating a reply.
	BlogPostId *string `json:"blogPostId,omitempty"`
	// ID of the containing page, if intending to create a top level footer comment. Do not provide if creating a reply.
	PageId *string `json:"pageId,omitempty"`
	// ID of the parent comment, if intending to create a reply. Do not provide if creating a top level comment.
	ParentCommentId         *string                                          `json:"parentCommentId,omitempty"`
	Body                    *CreateFooterCommentModelBody                    `json:"body,omitempty"`
	InlineCommentProperties *CreateInlineCommentModelInlineCommentProperties `json:"inlineCommentProperties,omitempty"`
}

// NewCreateInlineCommentModel instantiates a new CreateInlineCommentModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateInlineCommentModel() *CreateInlineCommentModel {
	this := CreateInlineCommentModel{}
	return &this
}

// NewCreateInlineCommentModelWithDefaults instantiates a new CreateInlineCommentModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateInlineCommentModelWithDefaults() *CreateInlineCommentModel {
	this := CreateInlineCommentModel{}
	return &this
}

// GetBlogPostId returns the BlogPostId field value if set, zero value otherwise.
func (o *CreateInlineCommentModel) GetBlogPostId() string {
	if o == nil || IsNil(o.BlogPostId) {
		var ret string
		return ret
	}
	return *o.BlogPostId
}

// GetBlogPostIdOk returns a tuple with the BlogPostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInlineCommentModel) GetBlogPostIdOk() (*string, bool) {
	if o == nil || IsNil(o.BlogPostId) {
		return nil, false
	}
	return o.BlogPostId, true
}

// HasBlogPostId returns a boolean if a field has been set.
func (o *CreateInlineCommentModel) HasBlogPostId() bool {
	if o != nil && !IsNil(o.BlogPostId) {
		return true
	}

	return false
}

// SetBlogPostId gets a reference to the given string and assigns it to the BlogPostId field.
func (o *CreateInlineCommentModel) SetBlogPostId(v string) {
	o.BlogPostId = &v
}

// GetPageId returns the PageId field value if set, zero value otherwise.
func (o *CreateInlineCommentModel) GetPageId() string {
	if o == nil || IsNil(o.PageId) {
		var ret string
		return ret
	}
	return *o.PageId
}

// GetPageIdOk returns a tuple with the PageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInlineCommentModel) GetPageIdOk() (*string, bool) {
	if o == nil || IsNil(o.PageId) {
		return nil, false
	}
	return o.PageId, true
}

// HasPageId returns a boolean if a field has been set.
func (o *CreateInlineCommentModel) HasPageId() bool {
	if o != nil && !IsNil(o.PageId) {
		return true
	}

	return false
}

// SetPageId gets a reference to the given string and assigns it to the PageId field.
func (o *CreateInlineCommentModel) SetPageId(v string) {
	o.PageId = &v
}

// GetParentCommentId returns the ParentCommentId field value if set, zero value otherwise.
func (o *CreateInlineCommentModel) GetParentCommentId() string {
	if o == nil || IsNil(o.ParentCommentId) {
		var ret string
		return ret
	}
	return *o.ParentCommentId
}

// GetParentCommentIdOk returns a tuple with the ParentCommentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInlineCommentModel) GetParentCommentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentCommentId) {
		return nil, false
	}
	return o.ParentCommentId, true
}

// HasParentCommentId returns a boolean if a field has been set.
func (o *CreateInlineCommentModel) HasParentCommentId() bool {
	if o != nil && !IsNil(o.ParentCommentId) {
		return true
	}

	return false
}

// SetParentCommentId gets a reference to the given string and assigns it to the ParentCommentId field.
func (o *CreateInlineCommentModel) SetParentCommentId(v string) {
	o.ParentCommentId = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *CreateInlineCommentModel) GetBody() CreateFooterCommentModelBody {
	if o == nil || IsNil(o.Body) {
		var ret CreateFooterCommentModelBody
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInlineCommentModel) GetBodyOk() (*CreateFooterCommentModelBody, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *CreateInlineCommentModel) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given CreateFooterCommentModelBody and assigns it to the Body field.
func (o *CreateInlineCommentModel) SetBody(v CreateFooterCommentModelBody) {
	o.Body = &v
}

// GetInlineCommentProperties returns the InlineCommentProperties field value if set, zero value otherwise.
func (o *CreateInlineCommentModel) GetInlineCommentProperties() CreateInlineCommentModelInlineCommentProperties {
	if o == nil || IsNil(o.InlineCommentProperties) {
		var ret CreateInlineCommentModelInlineCommentProperties
		return ret
	}
	return *o.InlineCommentProperties
}

// GetInlineCommentPropertiesOk returns a tuple with the InlineCommentProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInlineCommentModel) GetInlineCommentPropertiesOk() (*CreateInlineCommentModelInlineCommentProperties, bool) {
	if o == nil || IsNil(o.InlineCommentProperties) {
		return nil, false
	}
	return o.InlineCommentProperties, true
}

// HasInlineCommentProperties returns a boolean if a field has been set.
func (o *CreateInlineCommentModel) HasInlineCommentProperties() bool {
	if o != nil && !IsNil(o.InlineCommentProperties) {
		return true
	}

	return false
}

// SetInlineCommentProperties gets a reference to the given CreateInlineCommentModelInlineCommentProperties and assigns it to the InlineCommentProperties field.
func (o *CreateInlineCommentModel) SetInlineCommentProperties(v CreateInlineCommentModelInlineCommentProperties) {
	o.InlineCommentProperties = &v
}

func (o CreateInlineCommentModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateInlineCommentModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BlogPostId) {
		toSerialize["blogPostId"] = o.BlogPostId
	}
	if !IsNil(o.PageId) {
		toSerialize["pageId"] = o.PageId
	}
	if !IsNil(o.ParentCommentId) {
		toSerialize["parentCommentId"] = o.ParentCommentId
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.InlineCommentProperties) {
		toSerialize["inlineCommentProperties"] = o.InlineCommentProperties
	}
	return toSerialize, nil
}

type NullableCreateInlineCommentModel struct {
	value *CreateInlineCommentModel
	isSet bool
}

func (v NullableCreateInlineCommentModel) Get() *CreateInlineCommentModel {
	return v.value
}

func (v *NullableCreateInlineCommentModel) Set(val *CreateInlineCommentModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateInlineCommentModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateInlineCommentModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateInlineCommentModel(val *CreateInlineCommentModel) *NullableCreateInlineCommentModel {
	return &NullableCreateInlineCommentModel{value: val, isSet: true}
}

func (v NullableCreateInlineCommentModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateInlineCommentModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
