/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package confluence

import (
	"encoding/json"
)

// checks if the CustomContentNestedBodyWrite type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomContentNestedBodyWrite{}

// CustomContentNestedBodyWrite Body of the custom content. Only one body format should be specified as the property for this object, e.g. `storage`.
type CustomContentNestedBodyWrite struct {
	Storage        *CustomContentBodyWrite `json:"storage,omitempty"`
	AtlasDocFormat *CustomContentBodyWrite `json:"atlas_doc_format,omitempty"`
	Raw            *CustomContentBodyWrite `json:"raw,omitempty"`
}

// NewCustomContentNestedBodyWrite instantiates a new CustomContentNestedBodyWrite object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomContentNestedBodyWrite() *CustomContentNestedBodyWrite {
	this := CustomContentNestedBodyWrite{}
	return &this
}

// NewCustomContentNestedBodyWriteWithDefaults instantiates a new CustomContentNestedBodyWrite object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomContentNestedBodyWriteWithDefaults() *CustomContentNestedBodyWrite {
	this := CustomContentNestedBodyWrite{}
	return &this
}

// GetStorage returns the Storage field value if set, zero value otherwise.
func (o *CustomContentNestedBodyWrite) GetStorage() CustomContentBodyWrite {
	if o == nil || IsNil(o.Storage) {
		var ret CustomContentBodyWrite
		return ret
	}
	return *o.Storage
}

// GetStorageOk returns a tuple with the Storage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentNestedBodyWrite) GetStorageOk() (*CustomContentBodyWrite, bool) {
	if o == nil || IsNil(o.Storage) {
		return nil, false
	}
	return o.Storage, true
}

// HasStorage returns a boolean if a field has been set.
func (o *CustomContentNestedBodyWrite) HasStorage() bool {
	if o != nil && !IsNil(o.Storage) {
		return true
	}

	return false
}

// SetStorage gets a reference to the given CustomContentBodyWrite and assigns it to the Storage field.
func (o *CustomContentNestedBodyWrite) SetStorage(v CustomContentBodyWrite) {
	o.Storage = &v
}

// GetAtlasDocFormat returns the AtlasDocFormat field value if set, zero value otherwise.
func (o *CustomContentNestedBodyWrite) GetAtlasDocFormat() CustomContentBodyWrite {
	if o == nil || IsNil(o.AtlasDocFormat) {
		var ret CustomContentBodyWrite
		return ret
	}
	return *o.AtlasDocFormat
}

// GetAtlasDocFormatOk returns a tuple with the AtlasDocFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentNestedBodyWrite) GetAtlasDocFormatOk() (*CustomContentBodyWrite, bool) {
	if o == nil || IsNil(o.AtlasDocFormat) {
		return nil, false
	}
	return o.AtlasDocFormat, true
}

// HasAtlasDocFormat returns a boolean if a field has been set.
func (o *CustomContentNestedBodyWrite) HasAtlasDocFormat() bool {
	if o != nil && !IsNil(o.AtlasDocFormat) {
		return true
	}

	return false
}

// SetAtlasDocFormat gets a reference to the given CustomContentBodyWrite and assigns it to the AtlasDocFormat field.
func (o *CustomContentNestedBodyWrite) SetAtlasDocFormat(v CustomContentBodyWrite) {
	o.AtlasDocFormat = &v
}

// GetRaw returns the Raw field value if set, zero value otherwise.
func (o *CustomContentNestedBodyWrite) GetRaw() CustomContentBodyWrite {
	if o == nil || IsNil(o.Raw) {
		var ret CustomContentBodyWrite
		return ret
	}
	return *o.Raw
}

// GetRawOk returns a tuple with the Raw field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentNestedBodyWrite) GetRawOk() (*CustomContentBodyWrite, bool) {
	if o == nil || IsNil(o.Raw) {
		return nil, false
	}
	return o.Raw, true
}

// HasRaw returns a boolean if a field has been set.
func (o *CustomContentNestedBodyWrite) HasRaw() bool {
	if o != nil && !IsNil(o.Raw) {
		return true
	}

	return false
}

// SetRaw gets a reference to the given CustomContentBodyWrite and assigns it to the Raw field.
func (o *CustomContentNestedBodyWrite) SetRaw(v CustomContentBodyWrite) {
	o.Raw = &v
}

func (o CustomContentNestedBodyWrite) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomContentNestedBodyWrite) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Storage) {
		toSerialize["storage"] = o.Storage
	}
	if !IsNil(o.AtlasDocFormat) {
		toSerialize["atlas_doc_format"] = o.AtlasDocFormat
	}
	if !IsNil(o.Raw) {
		toSerialize["raw"] = o.Raw
	}
	return toSerialize, nil
}

type NullableCustomContentNestedBodyWrite struct {
	value *CustomContentNestedBodyWrite
	isSet bool
}

func (v NullableCustomContentNestedBodyWrite) Get() *CustomContentNestedBodyWrite {
	return v.value
}

func (v *NullableCustomContentNestedBodyWrite) Set(val *CustomContentNestedBodyWrite) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomContentNestedBodyWrite) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomContentNestedBodyWrite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomContentNestedBodyWrite(val *CustomContentNestedBodyWrite) *NullableCustomContentNestedBodyWrite {
	return &NullableCustomContentNestedBodyWrite{value: val, isSet: true}
}

func (v NullableCustomContentNestedBodyWrite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomContentNestedBodyWrite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
