/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package confluence

import (
	"encoding/json"
)

// checks if the BlogPostCommentModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlogPostCommentModel{}

// BlogPostCommentModel struct for BlogPostCommentModel
type BlogPostCommentModel struct {
	Id     *PageCommentModelId `json:"id,omitempty"`
	Status *ContentStatus      `json:"status,omitempty"`
	// Title of the comment.
	Title      *string                         `json:"title,omitempty"`
	BlogPostId *BlogPostCommentModelBlogPostId `json:"blogPostId,omitempty"`
	Version    *Version                        `json:"version,omitempty"`
	Body       *Body                           `json:"body,omitempty"`
}

// NewBlogPostCommentModel instantiates a new BlogPostCommentModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlogPostCommentModel() *BlogPostCommentModel {
	this := BlogPostCommentModel{}
	return &this
}

// NewBlogPostCommentModelWithDefaults instantiates a new BlogPostCommentModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlogPostCommentModelWithDefaults() *BlogPostCommentModel {
	this := BlogPostCommentModel{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BlogPostCommentModel) GetId() PageCommentModelId {
	if o == nil || IsNil(o.Id) {
		var ret PageCommentModelId
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlogPostCommentModel) GetIdOk() (*PageCommentModelId, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BlogPostCommentModel) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given PageCommentModelId and assigns it to the Id field.
func (o *BlogPostCommentModel) SetId(v PageCommentModelId) {
	o.Id = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *BlogPostCommentModel) GetStatus() ContentStatus {
	if o == nil || IsNil(o.Status) {
		var ret ContentStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlogPostCommentModel) GetStatusOk() (*ContentStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BlogPostCommentModel) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ContentStatus and assigns it to the Status field.
func (o *BlogPostCommentModel) SetStatus(v ContentStatus) {
	o.Status = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *BlogPostCommentModel) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlogPostCommentModel) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *BlogPostCommentModel) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *BlogPostCommentModel) SetTitle(v string) {
	o.Title = &v
}

// GetBlogPostId returns the BlogPostId field value if set, zero value otherwise.
func (o *BlogPostCommentModel) GetBlogPostId() BlogPostCommentModelBlogPostId {
	if o == nil || IsNil(o.BlogPostId) {
		var ret BlogPostCommentModelBlogPostId
		return ret
	}
	return *o.BlogPostId
}

// GetBlogPostIdOk returns a tuple with the BlogPostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlogPostCommentModel) GetBlogPostIdOk() (*BlogPostCommentModelBlogPostId, bool) {
	if o == nil || IsNil(o.BlogPostId) {
		return nil, false
	}
	return o.BlogPostId, true
}

// HasBlogPostId returns a boolean if a field has been set.
func (o *BlogPostCommentModel) HasBlogPostId() bool {
	if o != nil && !IsNil(o.BlogPostId) {
		return true
	}

	return false
}

// SetBlogPostId gets a reference to the given BlogPostCommentModelBlogPostId and assigns it to the BlogPostId field.
func (o *BlogPostCommentModel) SetBlogPostId(v BlogPostCommentModelBlogPostId) {
	o.BlogPostId = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *BlogPostCommentModel) GetVersion() Version {
	if o == nil || IsNil(o.Version) {
		var ret Version
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlogPostCommentModel) GetVersionOk() (*Version, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *BlogPostCommentModel) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given Version and assigns it to the Version field.
func (o *BlogPostCommentModel) SetVersion(v Version) {
	o.Version = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *BlogPostCommentModel) GetBody() Body {
	if o == nil || IsNil(o.Body) {
		var ret Body
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlogPostCommentModel) GetBodyOk() (*Body, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *BlogPostCommentModel) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given Body and assigns it to the Body field.
func (o *BlogPostCommentModel) SetBody(v Body) {
	o.Body = &v
}

func (o BlogPostCommentModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlogPostCommentModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.BlogPostId) {
		toSerialize["blogPostId"] = o.BlogPostId
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	return toSerialize, nil
}

type NullableBlogPostCommentModel struct {
	value *BlogPostCommentModel
	isSet bool
}

func (v NullableBlogPostCommentModel) Get() *BlogPostCommentModel {
	return v.value
}

func (v *NullableBlogPostCommentModel) Set(val *BlogPostCommentModel) {
	v.value = val
	v.isSet = true
}

func (v NullableBlogPostCommentModel) IsSet() bool {
	return v.isSet
}

func (v *NullableBlogPostCommentModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlogPostCommentModel(val *BlogPostCommentModel) *NullableBlogPostCommentModel {
	return &NullableBlogPostCommentModel{value: val, isSet: true}
}

func (v NullableBlogPostCommentModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlogPostCommentModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
