/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package confluence

import (
	"encoding/json"
)

// checks if the CustomContentBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomContentBody{}

// CustomContentBody Contains fields for each representation type requested.
type CustomContentBody struct {
	Raw            *BodyType `json:"raw,omitempty"`
	Storage        *BodyType `json:"storage,omitempty"`
	AtlasDocFormat *BodyType `json:"atlas_doc_format,omitempty"`
}

// NewCustomContentBody instantiates a new CustomContentBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomContentBody() *CustomContentBody {
	this := CustomContentBody{}
	return &this
}

// NewCustomContentBodyWithDefaults instantiates a new CustomContentBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomContentBodyWithDefaults() *CustomContentBody {
	this := CustomContentBody{}
	return &this
}

// GetRaw returns the Raw field value if set, zero value otherwise.
func (o *CustomContentBody) GetRaw() BodyType {
	if o == nil || IsNil(o.Raw) {
		var ret BodyType
		return ret
	}
	return *o.Raw
}

// GetRawOk returns a tuple with the Raw field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentBody) GetRawOk() (*BodyType, bool) {
	if o == nil || IsNil(o.Raw) {
		return nil, false
	}
	return o.Raw, true
}

// HasRaw returns a boolean if a field has been set.
func (o *CustomContentBody) HasRaw() bool {
	if o != nil && !IsNil(o.Raw) {
		return true
	}

	return false
}

// SetRaw gets a reference to the given BodyType and assigns it to the Raw field.
func (o *CustomContentBody) SetRaw(v BodyType) {
	o.Raw = &v
}

// GetStorage returns the Storage field value if set, zero value otherwise.
func (o *CustomContentBody) GetStorage() BodyType {
	if o == nil || IsNil(o.Storage) {
		var ret BodyType
		return ret
	}
	return *o.Storage
}

// GetStorageOk returns a tuple with the Storage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentBody) GetStorageOk() (*BodyType, bool) {
	if o == nil || IsNil(o.Storage) {
		return nil, false
	}
	return o.Storage, true
}

// HasStorage returns a boolean if a field has been set.
func (o *CustomContentBody) HasStorage() bool {
	if o != nil && !IsNil(o.Storage) {
		return true
	}

	return false
}

// SetStorage gets a reference to the given BodyType and assigns it to the Storage field.
func (o *CustomContentBody) SetStorage(v BodyType) {
	o.Storage = &v
}

// GetAtlasDocFormat returns the AtlasDocFormat field value if set, zero value otherwise.
func (o *CustomContentBody) GetAtlasDocFormat() BodyType {
	if o == nil || IsNil(o.AtlasDocFormat) {
		var ret BodyType
		return ret
	}
	return *o.AtlasDocFormat
}

// GetAtlasDocFormatOk returns a tuple with the AtlasDocFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentBody) GetAtlasDocFormatOk() (*BodyType, bool) {
	if o == nil || IsNil(o.AtlasDocFormat) {
		return nil, false
	}
	return o.AtlasDocFormat, true
}

// HasAtlasDocFormat returns a boolean if a field has been set.
func (o *CustomContentBody) HasAtlasDocFormat() bool {
	if o != nil && !IsNil(o.AtlasDocFormat) {
		return true
	}

	return false
}

// SetAtlasDocFormat gets a reference to the given BodyType and assigns it to the AtlasDocFormat field.
func (o *CustomContentBody) SetAtlasDocFormat(v BodyType) {
	o.AtlasDocFormat = &v
}

func (o CustomContentBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomContentBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Raw) {
		toSerialize["raw"] = o.Raw
	}
	if !IsNil(o.Storage) {
		toSerialize["storage"] = o.Storage
	}
	if !IsNil(o.AtlasDocFormat) {
		toSerialize["atlas_doc_format"] = o.AtlasDocFormat
	}
	return toSerialize, nil
}

type NullableCustomContentBody struct {
	value *CustomContentBody
	isSet bool
}

func (v NullableCustomContentBody) Get() *CustomContentBody {
	return v.value
}

func (v *NullableCustomContentBody) Set(val *CustomContentBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomContentBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomContentBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomContentBody(val *CustomContentBody) *NullableCustomContentBody {
	return &NullableCustomContentBody{value: val, isSet: true}
}

func (v NullableCustomContentBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomContentBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
