/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package confluence

import (
	"encoding/json"
)

// checks if the UpdateCustomContentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCustomContentRequest{}

// UpdateCustomContentRequest struct for UpdateCustomContentRequest
type UpdateCustomContentRequest struct {
	// Id of custom content.
	Id string `json:"id"`
	// Type of custom content.
	Type string `json:"type"`
	// The status of the custom content
	Status string `json:"status"`
	// ID of the containing space
	SpaceId *string `json:"spaceId,omitempty"`
	// ID of the containing page
	PageId *string `json:"pageId,omitempty"`
	// ID of the containing Blog Post
	BlogPostId *string `json:"blogPostId,omitempty"`
	// ID of the containing custom content
	CustomContentId *string `json:"customContentId,omitempty"`
	// Title of the custom content
	Title   string                         `json:"title"`
	Body    CreateCustomContentRequestBody `json:"body"`
	Version UpdateBlogPostRequestVersion   `json:"version"`
}

// NewUpdateCustomContentRequest instantiates a new UpdateCustomContentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCustomContentRequest(id string, type_ string, status string, title string, body CreateCustomContentRequestBody, version UpdateBlogPostRequestVersion) *UpdateCustomContentRequest {
	this := UpdateCustomContentRequest{}
	this.Id = id
	this.Type = type_
	this.Status = status
	this.Title = title
	this.Body = body
	this.Version = version
	return &this
}

// NewUpdateCustomContentRequestWithDefaults instantiates a new UpdateCustomContentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCustomContentRequestWithDefaults() *UpdateCustomContentRequest {
	this := UpdateCustomContentRequest{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateCustomContentRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateCustomContentRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateCustomContentRequest) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdateCustomContentRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateCustomContentRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateCustomContentRequest) SetType(v string) {
	o.Type = v
}

// GetStatus returns the Status field value
func (o *UpdateCustomContentRequest) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateCustomContentRequest) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateCustomContentRequest) SetStatus(v string) {
	o.Status = v
}

// GetSpaceId returns the SpaceId field value if set, zero value otherwise.
func (o *UpdateCustomContentRequest) GetSpaceId() string {
	if o == nil || IsNil(o.SpaceId) {
		var ret string
		return ret
	}
	return *o.SpaceId
}

// GetSpaceIdOk returns a tuple with the SpaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCustomContentRequest) GetSpaceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SpaceId) {
		return nil, false
	}
	return o.SpaceId, true
}

// HasSpaceId returns a boolean if a field has been set.
func (o *UpdateCustomContentRequest) HasSpaceId() bool {
	if o != nil && !IsNil(o.SpaceId) {
		return true
	}

	return false
}

// SetSpaceId gets a reference to the given string and assigns it to the SpaceId field.
func (o *UpdateCustomContentRequest) SetSpaceId(v string) {
	o.SpaceId = &v
}

// GetPageId returns the PageId field value if set, zero value otherwise.
func (o *UpdateCustomContentRequest) GetPageId() string {
	if o == nil || IsNil(o.PageId) {
		var ret string
		return ret
	}
	return *o.PageId
}

// GetPageIdOk returns a tuple with the PageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCustomContentRequest) GetPageIdOk() (*string, bool) {
	if o == nil || IsNil(o.PageId) {
		return nil, false
	}
	return o.PageId, true
}

// HasPageId returns a boolean if a field has been set.
func (o *UpdateCustomContentRequest) HasPageId() bool {
	if o != nil && !IsNil(o.PageId) {
		return true
	}

	return false
}

// SetPageId gets a reference to the given string and assigns it to the PageId field.
func (o *UpdateCustomContentRequest) SetPageId(v string) {
	o.PageId = &v
}

// GetBlogPostId returns the BlogPostId field value if set, zero value otherwise.
func (o *UpdateCustomContentRequest) GetBlogPostId() string {
	if o == nil || IsNil(o.BlogPostId) {
		var ret string
		return ret
	}
	return *o.BlogPostId
}

// GetBlogPostIdOk returns a tuple with the BlogPostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCustomContentRequest) GetBlogPostIdOk() (*string, bool) {
	if o == nil || IsNil(o.BlogPostId) {
		return nil, false
	}
	return o.BlogPostId, true
}

// HasBlogPostId returns a boolean if a field has been set.
func (o *UpdateCustomContentRequest) HasBlogPostId() bool {
	if o != nil && !IsNil(o.BlogPostId) {
		return true
	}

	return false
}

// SetBlogPostId gets a reference to the given string and assigns it to the BlogPostId field.
func (o *UpdateCustomContentRequest) SetBlogPostId(v string) {
	o.BlogPostId = &v
}

// GetCustomContentId returns the CustomContentId field value if set, zero value otherwise.
func (o *UpdateCustomContentRequest) GetCustomContentId() string {
	if o == nil || IsNil(o.CustomContentId) {
		var ret string
		return ret
	}
	return *o.CustomContentId
}

// GetCustomContentIdOk returns a tuple with the CustomContentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCustomContentRequest) GetCustomContentIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomContentId) {
		return nil, false
	}
	return o.CustomContentId, true
}

// HasCustomContentId returns a boolean if a field has been set.
func (o *UpdateCustomContentRequest) HasCustomContentId() bool {
	if o != nil && !IsNil(o.CustomContentId) {
		return true
	}

	return false
}

// SetCustomContentId gets a reference to the given string and assigns it to the CustomContentId field.
func (o *UpdateCustomContentRequest) SetCustomContentId(v string) {
	o.CustomContentId = &v
}

// GetTitle returns the Title field value
func (o *UpdateCustomContentRequest) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *UpdateCustomContentRequest) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *UpdateCustomContentRequest) SetTitle(v string) {
	o.Title = v
}

// GetBody returns the Body field value
func (o *UpdateCustomContentRequest) GetBody() CreateCustomContentRequestBody {
	if o == nil {
		var ret CreateCustomContentRequestBody
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *UpdateCustomContentRequest) GetBodyOk() (*CreateCustomContentRequestBody, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *UpdateCustomContentRequest) SetBody(v CreateCustomContentRequestBody) {
	o.Body = v
}

// GetVersion returns the Version field value
func (o *UpdateCustomContentRequest) GetVersion() UpdateBlogPostRequestVersion {
	if o == nil {
		var ret UpdateBlogPostRequestVersion
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *UpdateCustomContentRequest) GetVersionOk() (*UpdateBlogPostRequestVersion, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *UpdateCustomContentRequest) SetVersion(v UpdateBlogPostRequestVersion) {
	o.Version = v
}

func (o UpdateCustomContentRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCustomContentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["status"] = o.Status
	if !IsNil(o.SpaceId) {
		toSerialize["spaceId"] = o.SpaceId
	}
	if !IsNil(o.PageId) {
		toSerialize["pageId"] = o.PageId
	}
	if !IsNil(o.BlogPostId) {
		toSerialize["blogPostId"] = o.BlogPostId
	}
	if !IsNil(o.CustomContentId) {
		toSerialize["customContentId"] = o.CustomContentId
	}
	toSerialize["title"] = o.Title
	toSerialize["body"] = o.Body
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

type NullableUpdateCustomContentRequest struct {
	value *UpdateCustomContentRequest
	isSet bool
}

func (v NullableUpdateCustomContentRequest) Get() *UpdateCustomContentRequest {
	return v.value
}

func (v *NullableUpdateCustomContentRequest) Set(val *UpdateCustomContentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCustomContentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCustomContentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCustomContentRequest(val *UpdateCustomContentRequest) *NullableUpdateCustomContentRequest {
	return &NullableUpdateCustomContentRequest{value: val, isSet: true}
}

func (v NullableUpdateCustomContentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCustomContentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
