/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package confluence

import (
	"encoding/json"
)

// checks if the BodyType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BodyType{}

// BodyType struct for BodyType
type BodyType struct {
	// Type of content representation used for the value field.
	Representation *string `json:"representation,omitempty"`
	// Body of the content, in the format found in the representation field.
	Value *string `json:"value,omitempty"`
}

// NewBodyType instantiates a new BodyType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBodyType() *BodyType {
	this := BodyType{}
	return &this
}

// NewBodyTypeWithDefaults instantiates a new BodyType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBodyTypeWithDefaults() *BodyType {
	this := BodyType{}
	return &this
}

// GetRepresentation returns the Representation field value if set, zero value otherwise.
func (o *BodyType) GetRepresentation() string {
	if o == nil || IsNil(o.Representation) {
		var ret string
		return ret
	}
	return *o.Representation
}

// GetRepresentationOk returns a tuple with the Representation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BodyType) GetRepresentationOk() (*string, bool) {
	if o == nil || IsNil(o.Representation) {
		return nil, false
	}
	return o.Representation, true
}

// HasRepresentation returns a boolean if a field has been set.
func (o *BodyType) HasRepresentation() bool {
	if o != nil && !IsNil(o.Representation) {
		return true
	}

	return false
}

// SetRepresentation gets a reference to the given string and assigns it to the Representation field.
func (o *BodyType) SetRepresentation(v string) {
	o.Representation = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *BodyType) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BodyType) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *BodyType) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *BodyType) SetValue(v string) {
	o.Value = &v
}

func (o BodyType) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BodyType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Representation) {
		toSerialize["representation"] = o.Representation
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableBodyType struct {
	value *BodyType
	isSet bool
}

func (v NullableBodyType) Get() *BodyType {
	return v.value
}

func (v *NullableBodyType) Set(val *BodyType) {
	v.value = val
	v.isSet = true
}

func (v NullableBodyType) IsSet() bool {
	return v.isSet
}

func (v *NullableBodyType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBodyType(val *BodyType) *NullableBodyType {
	return &NullableBodyType{value: val, isSet: true}
}

func (v NullableBodyType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBodyType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
